name: HTTP Kexa Action
#on:
#  schedule:
#    - cron: '40 8 * * *'   # every day at 8:40 am
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Kexa Action
        uses: 4urcloud/Kexa_githubAction@1.8.2
        id: kexa
        with:
          ENV_VARS: |
            MYOWNRULES="./rules"
            NODE_CONFIG_TS_ENV=http

      - name: Check Kexa Action Result
        if: steps.kexa.outcome != 'success'
        run: |
          echo "Kexa Action failed with exit code $?. Exiting..."
          exit 1
