name: Workspace (multiple conf) Kexa Action
#on:
#  schedule:
#    - cron: '20 8 * * *'   # every day at 8:20 am
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Kexa Action
        uses: kexa-io/git-action@1.8.6-stable
        id: kexa
        with:
          ENV_VARS: |
            MYOWNRULES="./rules"
            NODE_CONFIG_TS_ENV=workspace
          GW1_WORKSPACECRED: ${{ secrets.GW1_WORKSPACECRED }}
          GW2_WORKSPACECRED: ${{ secrets.GW1_WORKSPACECRED }}
          WORKSPACECRED_PREFIX: "GW1_,GW2_"

      - name: Check Kexa Action Result
        if: steps.kexa.outcome != 'success'
        run: |
          echo "Kexa Action failed with exit code $?. Exiting..."
          exit 1
